Description: Instance Profile for ASG servers

Parameters:

  Project:
    Description: Name 
    Type: String
  
  Env:
    Description: Env
    Type: String

  CIDR:
    Description: VPC CIDR
    Type: String

  PublicCIDR1:
    Description: PublicCIDR1
    Type: String

  PublicCIDR2:
    Description: PublicCIDR2
    Type: String

  PrivateCIDR1:
    Description: PrivateCIDR1
    Type: String

  PrivateCIDR2:
    Description: PrivateCIDR2
    Type: String

Resources:

  AppVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: Default
      Tags:
        - Key: Name
          Value: !Sub appvpc-${Project}-${Env}

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: !Ref PublicCIDR1
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub appvpc-${Project}-${Env}
      VpcId: !Ref AppVPC

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ]
      CidrBlock: !Ref PublicCIDR2
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub appvpc-${Project}-${Env}
      VpcId: !Ref AppVPC

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: !Ref PrivateCIDR1
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub appvpc-${Project}-${Env}
      VpcId: !Ref AppVPC

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: !Ref PrivateCIDR2
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub appvpc-${Project}-${Env}
      VpcId: !Ref AppVPC

Outputs:
  VPC:
    Value: !Ref appVPC
  PublicSub1:
    Value: !Ref PublicSubnet1
  PublicSub2:
    Value: !Ref PublicSubnet2
  PrivateSub1:
    Value:  !Ref PrivateSubnet1
  PrivateSub2:
    Value:  !Ref PrivateSubnet2
  PublicSub:
    Value: !Join [",", [ !Ref PublicSubnet1, !Ref PublicSubnet2 ]]
  PrivateSub:
    Value: !Join [",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ]]